version: "2"
services:
  tetrifacttestmount:
    image: shukriadams/tetrifact:1.8.1-test
    container_name: tetrifact-demo
    restart: unless-stopped
    environment:
      ASPNETCORE_URLS : http://*:5000
    ports:
    - "49023:5000"
    volumes:
        - ./data:/var/tetrifact/data/:rw    
    