# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/bionic64"
    config.vm.synced_folder "./../..", "/vagrant"
    config.vm.provision :shell, path: "./../provision.sh"
    config.vm.network "forwarded_port", guest: 49023, host: 49023
    config.vm.network "forwarded_port", guest: 49024, host: 49024
    config.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", 1048]
        v.name = "tetrifact-tools"
    end

end
