name: builds 
on: 
    push:
        tags:
            - '*'
jobs:

    buildWin64:
        runs-on: windows-2022
        steps:
        - uses: actions/checkout@v1
          with:
            node-version: 20
        - name: builds and pushes the container
          run: sh ./build.sh 
          env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
