name: builds 
on: 
    push:
        tags:
            - '*'
jobs:

    buildWin64:
        runs-on: windows-2022
        container:
          image: shukriadams/windows-node20-build:0.0.1
        steps:

        - uses: actions/checkout@v4

        - name: builds and push binaries
          shell: powershell
          run: ./build.ps1 --token $GH_TOKEN
          env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
